<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Employee;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'first_name' => 'MARJORIE MAE',
                'middle_name' => 'VILLAFUENTE',
                'last_name' => 'ALISOSO',
                'contract_start' => '2025-03-03',
                'contract_type' => 'PROBATIONARY',
                'role' => 'ADMIN',
                'location' => 'MAIN',
                'sss' => '35-2770266-8',
                'philhealth' => '16-253233815-8',
                'pagibig' => '1213-28380-847',
                'birthdate' => '2000-08-14',
                'status' => 'active',
                'notes' => 'New admin staff member'
            ],
            [
                'first_name' => 'GEOFFREY',
                'middle_name' => 'QUILATAN',
                'last_name' => 'TABLADA',
                'contract_start' => '2024-09-16',
                'contract_type' => 'REGULAR',
                'role' => 'ADMIN SALES',
                'location' => 'MAIN',
                'sss' => '34-8505570-3',
                'philhealth' => '01-026515310-6',
                'pagibig' => '1212-486718-09',
                'birthdate' => '1999-01-27',
                'status' => 'active',
                'notes' => 'Experienced admin sales staff'
            ],
            [
                'first_name' => 'KRISTOFFER JOHN IAN',
                'middle_name' => 'N/A',
                'last_name' => 'BOLAGAO',
                'contract_start' => '2025-06-25',
                'contract_type' => 'PROBATIONARY',
                'role' => 'BUFFER - GEN. STAFF',
                'location' => 'EXTENSION',
                'sss' => null,
                'philhealth' => null,
                'pagibig' => null,
                'birthdate' => '1985-01-10',
                'status' => 'active',
                'notes' => 'General staff member at extension branch'
            ],
            [
                'first_name' => 'MARIA',
                'middle_name' => 'SANTOS',
                'last_name' => 'CRUZ',
                'contract_start' => '2024-11-15',
                'contract_type' => 'REGULAR',
                'role' => 'DATA ENCODER',
                'location' => 'MAIN',
                'sss' => '35-1234567-8',
                'philhealth' => '16-123456789-0',
                'pagibig' => '1213-123456-78',
                'birthdate' => '1995-05-20',
                'status' => 'active',
                'notes' => 'Data entry specialist'
            ],
            [
                'first_name' => 'JUAN',
                'middle_name' => 'DELA',
                'last_name' => 'CRUZ',
                'contract_start' => '2024-08-01',
                'contract_type' => 'REGULAR',
                'role' => 'DRIVER',
                'location' => 'WAREHOUSE',
                'sss' => '35-2345678-9',
                'philhealth' => '16-234567890-1',
                'pagibig' => '1213-234567-89',
                'birthdate' => '1988-12-03',
                'status' => 'active',
                'notes' => 'Delivery driver for warehouse operations'
            ],
            [
                'first_name' => 'PEDRO',
                'middle_name' => 'GARCIA',
                'last_name' => 'MARTINEZ',
                'contract_start' => '2024-07-10',
                'contract_type' => 'REGULAR',
                'role' => 'MECHANIC',
                'location' => 'ANNEX',
                'sss' => '35-3456789-0',
                'philhealth' => '16-345678901-2',
                'pagibig' => '1213-345678-90',
                'birthdate' => '1990-03-15',
                'status' => 'active',
                'notes' => 'Automotive mechanic at annex location'
            ],
            [
                'first_name' => 'ANA',
                'middle_name' => 'RODRIGUEZ',
                'last_name' => 'LOPEZ',
                'contract_start' => '2025-01-15',
                'contract_type' => 'PROBATIONARY',
                'role' => 'SALES ASST. - GEN. STAFF',
                'location' => 'PREMIUM',
                'sss' => null,
                'philhealth' => null,
                'pagibig' => null,
                'birthdate' => '1992-07-22',
                'status' => 'active',
                'notes' => 'Sales assistant at premium location'
            ],
            [
                'first_name' => 'CARLOS',
                'middle_name' => 'MIGUEL',
                'last_name' => 'SANTOS',
                'contract_start' => '2024-12-01',
                'contract_type' => 'REGULAR',
                'role' => 'ADMIN',
                'location' => 'MAIN',
                'sss' => '35-4567890-1',
                'philhealth' => '16-456789012-3',
                'pagibig' => '1213-456789-01',
                'birthdate' => '1987-09-08',
                'status' => 'active',
                'notes' => 'Senior admin staff'
            ],
            [
                'first_name' => 'SOPHIA',
                'middle_name' => 'ISABEL',
                'last_name' => 'GONZALES',
                'contract_start' => '2025-02-10',
                'contract_type' => 'PROBATIONARY',
                'role' => 'DATA ENCODER',
                'location' => 'EXTENSION',
                'sss' => null,
                'philhealth' => null,
                'pagibig' => null,
                'birthdate' => '1996-11-30',
                'status' => 'active',
                'notes' => 'New data encoder at extension'
            ],
            [
                'first_name' => 'MIGUEL',
                'middle_name' => 'ANGEL',
                'last_name' => 'TORRES',
                'contract_start' => '2024-10-20',
                'contract_type' => 'REGULAR',
                'role' => 'DRIVER',
                'location' => 'MAIN',
                'sss' => '35-5678901-2',
                'philhealth' => '16-567890123-4',
                'pagibig' => '1213-567890-12',
                'birthdate' => '1989-04-12',
                'status' => 'active',
                'notes' => 'Main branch driver'
            ],
            [
                'first_name' => 'ISABELLA',
                'middle_name' => 'ROSE',
                'last_name' => 'RAMIREZ',
                'contract_start' => '2024-06-05',
                'contract_type' => 'REGULAR',
                'role' => 'ADMIN SALES',
                'location' => 'PREMIUM',
                'sss' => '35-6789012-3',
                'philhealth' => '16-678901234-5',
                'pagibig' => '1213-678901-23',
                'birthdate' => '1991-02-18',
                'status' => 'active',
                'notes' => 'Admin sales at premium location'
            ],
            [
                'first_name' => 'ANTONIO',
                'middle_name' => 'JOSE',
                'last_name' => 'HERNANDEZ',
                'contract_start' => '2025-04-01',
                'contract_type' => 'PROBATIONARY',
                'role' => 'MECHANIC',
                'location' => 'WAREHOUSE',
                'sss' => null,
                'philhealth' => null,
                'pagibig' => null,
                'birthdate' => '1993-08-25',
                'status' => 'active',
                'notes' => 'Warehouse mechanic'
            ],
            [
                'first_name' => 'VALENTINA',
                'middle_name' => 'MARIA',
                'last_name' => 'FLORES',
                'contract_start' => '2024-09-30',
                'contract_type' => 'REGULAR',
                'role' => 'SALES ASST. - GEN. STAFF',
                'location' => 'ANNEX',
                'sss' => '35-7890123-4',
                'philhealth' => '16-789012345-6',
                'pagibig' => '1213-789012-34',
                'birthdate' => '1994-06-14',
                'status' => 'active',
                'notes' => 'Sales assistant at annex'
            ],
            [
                'first_name' => 'DIEGO',
                'middle_name' => 'ALEJANDRO',
                'last_name' => 'MORALES',
                'contract_start' => '2024-11-20',
                'contract_type' => 'REGULAR',
                'role' => 'BUFFER - GEN. STAFF',
                'location' => 'MAIN',
                'sss' => '35-8901234-5',
                'philhealth' => '16-890123456-7',
                'pagibig' => '1213-890123-45',
                'birthdate' => '1986-10-07',
                'status' => 'active',
                'notes' => 'General staff at main office'
            ],
            [
                'first_name' => 'CAMILA',
                'middle_name' => 'SOFIA',
                'last_name' => 'VARGAS',
                'contract_start' => '2025-03-15',
                'contract_type' => 'PROBATIONARY',
                'role' => 'DATA ENCODER',
                'location' => 'PREMIUM',
                'sss' => null,
                'philhealth' => null,
                'pagibig' => null,
                'birthdate' => '1997-01-28',
                'status' => 'active',
                'notes' => 'Data encoder at premium location'
            ],
            [
                'first_name' => 'SANTIAGO',
                'middle_name' => 'CARLOS',
                'last_name' => 'JIMENEZ',
                'contract_start' => '2024-08-15',
                'contract_type' => 'REGULAR',
                'role' => 'DRIVER',
                'location' => 'EXTENSION',
                'sss' => '35-9012345-6',
                'philhealth' => '16-901234567-8',
                'pagibig' => '1213-901234-56',
                'birthdate' => '1990-12-11',
                'status' => 'active',
                'notes' => 'Extension branch driver'
            ],
            [
                'first_name' => 'VALERIA',
                'middle_name' => 'ELENA',
                'last_name' => 'CASTRO',
                'contract_start' => '2024-07-25',
                'contract_type' => 'REGULAR',
                'role' => 'ADMIN',
                'location' => 'ANNEX',
                'sss' => '35-0123456-7',
                'philhealth' => '16-012345678-9',
                'pagibig' => '1213-012345-67',
                'birthdate' => '1988-05-03',
                'status' => 'active',
                'notes' => 'Admin at annex location'
            ],
            [
                'first_name' => 'MATEO',
                'middle_name' => 'GABRIEL',
                'last_name' => 'RUIZ',
                'contract_start' => '2025-01-05',
                'contract_type' => 'PROBATIONARY',
                'role' => 'MECHANIC',
                'location' => 'MAIN',
                'sss' => null,
                'philhealth' => null,
                'pagibig' => null,
                'birthdate' => '1995-09-16',
                'status' => 'active',
                'notes' => 'Mechanic trainee at main location'
            ],
            [
                'first_name' => 'LUCIA',
                'middle_name' => 'FERNANDA',
                'last_name' => 'DIAZ',
                'contract_start' => '2024-12-10',
                'contract_type' => 'REGULAR',
                'role' => 'SALES ASST. - GEN. STAFF',
                'location' => 'WAREHOUSE',
                'sss' => '35-1234567-8',
                'philhealth' => '16-123456789-0',
                'pagibig' => '1213-123456-78',
                'birthdate' => '1992-03-24',
                'status' => 'active',
                'notes' => 'Sales assistant at warehouse'
            ],
            [
                'first_name' => 'NICOLAS',
                'middle_name' => 'SEBASTIAN',
                'last_name' => 'HERRERA',
                'contract_start' => '2024-10-05',
                'contract_type' => 'REGULAR',
                'role' => 'ADMIN SALES',
                'location' => 'EXTENSION',
                'sss' => '35-2345678-9',
                'philhealth' => '16-234567890-1',
                'pagibig' => '1213-234567-89',
                'birthdate' => '1987-07-19',
                'status' => 'active',
                'notes' => 'Admin sales at extension'
            ],
            [
                'first_name' => 'EMILIA',
                'middle_name' => 'VICTORIA',
                'last_name' => 'MORENO',
                'contract_start' => '2025-02-20',
                'contract_type' => 'PROBATIONARY',
                'role' => 'BUFFER - GEN. STAFF',
                'location' => 'PREMIUM',
                'sss' => null,
                'philhealth' => null,
                'pagibig' => null,
                'birthdate' => '1996-11-02',
                'status' => 'active',
                'notes' => 'General staff at premium location'
            ],
            [
                'first_name' => 'LEONARDO',
                'middle_name' => 'ANTONIO',
                'last_name' => 'GUTIERREZ',
                'contract_start' => '2024-09-10',
                'contract_type' => 'REGULAR',
                'role' => 'DATA ENCODER',
                'location' => 'MAIN',
                'sss' => '35-3456789-0',
                'philhealth' => '16-345678901-2',
                'pagibig' => '1213-345678-90',
                'birthdate' => '1989-04-27',
                'status' => 'active',
                'notes' => 'Senior data encoder'
            ],
            [
                'first_name' => 'ADRIANA',
                'middle_name' => 'ISABEL',
                'last_name' => 'RAMOS',
                'contract_start' => '2024-11-25',
                'contract_type' => 'REGULAR',
                'role' => 'DRIVER',
                'location' => 'ANNEX',
                'sss' => '35-4567890-1',
                'philhealth' => '16-456789012-3',
                'pagibig' => '1213-456789-01',
                'birthdate' => '1991-08-13',
                'status' => 'active',
                'notes' => 'Driver at annex location'
            ],
            [
                'first_name' => 'GABRIEL',
                'middle_name' => 'ALEXANDER',
                'last_name' => 'MENDOZA',
                'contract_start' => '2025-05-01',
                'contract_type' => 'PROBATIONARY',
                'role' => 'MECHANIC',
                'location' => 'EXTENSION',
                'sss' => null,
                'philhealth' => null,
                'pagibig' => null,
                'birthdate' => '1994-12-05',
                'status' => 'inactive',
                'notes' => 'Former mechanic - resigned'
            ]
        ];

        foreach ($employees as $employee) {
            Employee::create($employee);
        }
    }
}