<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SalesAgent;
use Carbon\Carbon;

class SalesAgentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $agents = [
            [
                'name' => 'John Michael Santos',
                'email' => 'john.santos@carempire.com',
                'phone' => '+63 917 123 4567',
                'sales_agent_id' => 'SA001',
                'department' => 'Sales',
                'position' => 'Senior Sales Agent',
                'hire_date' => '2022-01-15',
                'commission_rate' => 5.5,
                'base_salary' => 25000.00,
                'address' => '123 Main Street, Quezon City, Metro Manila',
                'emergency_contact_name' => 'Maria Santos',
                'emergency_contact_phone' => '+63 917 987 6543',
                'status' => 'active',
                'notes' => 'Top performer for 3 consecutive quarters. Specializes in luxury vehicles.'
            ],
            [
                'name' => 'Sarah Jane Rodriguez',
                'email' => 'sarah.rodriguez@carempire.com',
                'phone' => '+63 918 234 5678',
                'sales_agent_id' => 'SA002',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2022-03-20',
                'commission_rate' => 4.0,
                'base_salary' => 22000.00,
                'address' => '456 Oak Avenue, Makati City, Metro Manila',
                'emergency_contact_name' => 'Carlos Rodriguez',
                'emergency_contact_phone' => '+63 918 876 5432',
                'status' => 'active',
                'notes' => 'Excellent customer service skills. Focuses on family vehicles.'
            ],
            [
                'name' => 'Michael David Chen',
                'email' => 'michael.chen@carempire.com',
                'phone' => '+63 919 345 6789',
                'sales_agent_id' => 'SA003',
                'department' => 'Sales',
                'position' => 'Sales Manager',
                'hire_date' => '2021-08-10',
                'commission_rate' => 6.0,
                'base_salary' => 35000.00,
                'address' => '789 Pine Street, Taguig City, Metro Manila',
                'emergency_contact_name' => 'Lisa Chen',
                'emergency_contact_phone' => '+63 919 765 4321',
                'status' => 'active',
                'notes' => 'Team leader with 5+ years experience. Manages 8 sales agents.'
            ],
            [
                'name' => 'Maria Elena Cruz',
                'email' => 'maria.cruz@carempire.com',
                'phone' => '+63 920 456 7890',
                'sales_agent_id' => 'SA004',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2022-06-05',
                'commission_rate' => 4.5,
                'base_salary' => 23000.00,
                'address' => '321 Elm Street, Pasig City, Metro Manila',
                'emergency_contact_name' => 'Roberto Cruz',
                'emergency_contact_phone' => '+63 920 654 3210',
                'status' => 'active',
                'notes' => 'New to the team but showing great potential. Specializes in compact cars.'
            ],
            [
                'name' => 'James Patrick Wilson',
                'email' => 'james.wilson@carempire.com',
                'phone' => '+63 921 567 8901',
                'sales_agent_id' => 'SA005',
                'department' => 'Sales',
                'position' => 'Senior Sales Agent',
                'hire_date' => '2021-11-30',
                'commission_rate' => 5.0,
                'base_salary' => 28000.00,
                'address' => '654 Maple Drive, Mandaluyong City, Metro Manila',
                'emergency_contact_name' => 'Jennifer Wilson',
                'emergency_contact_phone' => '+63 921 543 2109',
                'status' => 'active',
                'notes' => 'Experienced in commercial vehicle sales. Strong negotiation skills.'
            ],
            [
                'name' => 'Ana Marie Garcia',
                'email' => 'ana.garcia@carempire.com',
                'phone' => '+63 922 678 9012',
                'sales_agent_id' => 'SA006',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2023-01-15',
                'commission_rate' => 3.5,
                'base_salary' => 20000.00,
                'address' => '987 Cedar Lane, San Juan City, Metro Manila',
                'emergency_contact_name' => 'Miguel Garcia',
                'emergency_contact_phone' => '+63 922 432 1098',
                'status' => 'active',
                'notes' => 'Fresh graduate with excellent communication skills. Learning quickly.'
            ],
            [
                'name' => 'Robert Anthony Lee',
                'email' => 'robert.lee@carempire.com',
                'phone' => '+63 923 789 0123',
                'sales_agent_id' => 'SA007',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2022-09-12',
                'commission_rate' => 4.2,
                'base_salary' => 22500.00,
                'address' => '147 Birch Street, Marikina City, Metro Manila',
                'emergency_contact_name' => 'Grace Lee',
                'emergency_contact_phone' => '+63 923 321 0987',
                'status' => 'active',
                'notes' => 'Strong technical knowledge of vehicles. Good with detailed explanations.'
            ],
            [
                'name' => 'Catherine Rose Martinez',
                'email' => 'catherine.martinez@carempire.com',
                'phone' => '+63 924 890 1234',
                'sales_agent_id' => 'SA008',
                'department' => 'Sales',
                'position' => 'Senior Sales Agent',
                'hire_date' => '2021-05-18',
                'commission_rate' => 5.8,
                'base_salary' => 30000.00,
                'address' => '258 Spruce Avenue, Las Piñas City, Metro Manila',
                'emergency_contact_name' => 'Antonio Martinez',
                'emergency_contact_phone' => '+63 924 210 9876',
                'status' => 'active',
                'notes' => 'Consistent top performer. Excellent at closing deals. Mentor to junior agents.'
            ],
            [
                'name' => 'David Christopher Kim',
                'email' => 'david.kim@carempire.com',
                'phone' => '+63 925 901 2345',
                'sales_agent_id' => 'SA009',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2022-12-01',
                'commission_rate' => 3.8,
                'base_salary' => 21000.00,
                'address' => '369 Walnut Street, Parañaque City, Metro Manila',
                'emergency_contact_name' => 'Sofia Kim',
                'emergency_contact_phone' => '+63 925 109 8765',
                'status' => 'active',
                'notes' => 'Bilingual (English and Korean). Good with international clients.'
            ],
            [
                'name' => 'Lisa Marie Thompson',
                'email' => 'lisa.thompson@carempire.com',
                'phone' => '+63 926 012 3456',
                'sales_agent_id' => 'SA010',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2023-03-08',
                'commission_rate' => 3.2,
                'base_salary' => 19500.00,
                'address' => '741 Cherry Lane, Muntinlupa City, Metro Manila',
                'emergency_contact_name' => 'William Thompson',
                'emergency_contact_phone' => '+63 926 098 7654',
                'status' => 'active',
                'notes' => 'Recent hire. Enthusiastic and eager to learn. Good with social media marketing.'
            ],
            [
                'name' => 'Mark Anthony Flores',
                'email' => 'mark.flores@carempire.com',
                'phone' => '+63 927 123 4567',
                'sales_agent_id' => 'SA011',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2022-07-25',
                'commission_rate' => 4.3,
                'base_salary' => 23500.00,
                'address' => '852 Poplar Drive, Caloocan City, Metro Manila',
                'emergency_contact_name' => 'Carmen Flores',
                'emergency_contact_phone' => '+63 927 987 6543',
                'status' => 'active',
                'notes' => 'Good relationship builder. Strong in follow-up and customer retention.'
            ],
            [
                'name' => 'Jennifer Lynn Anderson',
                'email' => 'jennifer.anderson@carempire.com',
                'phone' => '+63 928 234 5678',
                'sales_agent_id' => 'SA012',
                'department' => 'Sales',
                'position' => 'Senior Sales Agent',
                'hire_date' => '2021-12-03',
                'commission_rate' => 5.2,
                'base_salary' => 27000.00,
                'address' => '963 Sycamore Street, Valenzuela City, Metro Manila',
                'emergency_contact_name' => 'Robert Anderson',
                'emergency_contact_phone' => '+63 928 876 5432',
                'status' => 'active',
                'notes' => 'Specializes in premium vehicles. Excellent product knowledge.'
            ],
            [
                'name' => 'Christopher Paul Reyes',
                'email' => 'christopher.reyes@carempire.com',
                'phone' => '+63 929 345 6789',
                'sales_agent_id' => 'SA013',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2023-05-20',
                'commission_rate' => 3.6,
                'base_salary' => 20500.00,
                'address' => '159 Hickory Lane, Malabon City, Metro Manila',
                'emergency_contact_name' => 'Patricia Reyes',
                'emergency_contact_phone' => '+63 929 765 4321',
                'status' => 'active',
                'notes' => 'Tech-savvy. Good with digital tools and CRM systems.'
            ],
            [
                'name' => 'Michelle Anne Torres',
                'email' => 'michelle.torres@carempire.com',
                'phone' => '+63 930 456 7890',
                'sales_agent_id' => 'SA014',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2022-04-14',
                'commission_rate' => 4.1,
                'base_salary' => 22800.00,
                'address' => '357 Magnolia Avenue, Navotas City, Metro Manila',
                'emergency_contact_name' => 'Jose Torres',
                'emergency_contact_phone' => '+63 930 654 3210',
                'status' => 'active',
                'notes' => 'Strong analytical skills. Good at identifying customer needs.'
            ],
            [
                'name' => 'Daniel Joseph Ramos',
                'email' => 'daniel.ramos@carempire.com',
                'phone' => '+63 931 567 8901',
                'sales_agent_id' => 'SA015',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2021-10-22',
                'commission_rate' => 4.7,
                'base_salary' => 24500.00,
                'address' => '468 Dogwood Street, Pateros, Metro Manila',
                'emergency_contact_name' => 'Elena Ramos',
                'emergency_contact_phone' => '+63 931 543 2109',
                'status' => 'active',
                'notes' => 'Experienced in fleet sales. Good with corporate clients.'
            ],
            [
                'name' => 'Stephanie Joy Hernandez',
                'email' => 'stephanie.hernandez@carempire.com',
                'phone' => '+63 932 678 9012',
                'sales_agent_id' => 'SA016',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2022-11-30',
                'commission_rate' => 3.9,
                'base_salary' => 21800.00,
                'address' => '579 Redwood Drive, Manila City, Metro Manila',
                'emergency_contact_name' => 'Manuel Hernandez',
                'emergency_contact_phone' => '+63 932 432 1098',
                'status' => 'active',
                'notes' => 'Good with first-time buyers. Patient and thorough in explanations.'
            ],
            [
                'name' => 'Kevin Michael Lopez',
                'email' => 'kevin.lopez@carempire.com',
                'phone' => '+63 933 789 0123',
                'sales_agent_id' => 'SA017',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2023-02-15',
                'commission_rate' => 3.4,
                'base_salary' => 20200.00,
                'address' => '680 Sequoia Lane, Pasay City, Metro Manila',
                'emergency_contact_name' => 'Rosa Lopez',
                'emergency_contact_phone' => '+63 933 321 0987',
                'status' => 'active',
                'notes' => 'Quick learner. Good at adapting to different customer personalities.'
            ],
            [
                'name' => 'Amanda Grace White',
                'email' => 'amanda.white@carempire.com',
                'phone' => '+63 934 890 1234',
                'sales_agent_id' => 'SA018',
                'department' => 'Sales',
                'position' => 'Senior Sales Agent',
                'hire_date' => '2021-07-08',
                'commission_rate' => 5.3,
                'base_salary' => 26500.00,
                'address' => '791 Ash Street, Makati City, Metro Manila',
                'emergency_contact_name' => 'Thomas White',
                'emergency_contact_phone' => '+63 934 210 9876',
                'status' => 'active',
                'notes' => 'Strong leadership qualities. Often assists in training new agents.'
            ],
            [
                'name' => 'Ryan Patrick Brown',
                'email' => 'ryan.brown@carempire.com',
                'phone' => '+63 935 901 2345',
                'sales_agent_id' => 'SA019',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2022-08-18',
                'commission_rate' => 4.4,
                'base_salary' => 23200.00,
                'address' => '802 Elm Avenue, Quezon City, Metro Manila',
                'emergency_contact_name' => 'Linda Brown',
                'emergency_contact_phone' => '+63 935 109 8765',
                'status' => 'active',
                'notes' => 'Good with financing options. Helps customers with loan applications.'
            ],
            [
                'name' => 'Nicole Marie Davis',
                'email' => 'nicole.davis@carempire.com',
                'phone' => '+63 936 012 3456',
                'sales_agent_id' => 'SA020',
                'department' => 'Sales',
                'position' => 'Sales Agent',
                'hire_date' => '2023-01-10',
                'commission_rate' => 3.7,
                'base_salary' => 20800.00,
                'address' => '913 Oak Drive, Taguig City, Metro Manila',
                'emergency_contact_name' => 'Michael Davis',
                'emergency_contact_phone' => '+63 936 098 7654',
                'status' => 'inactive',
                'notes' => 'Recently resigned. Was a promising agent with good potential.'
            ]
        ];

        foreach ($agents as $agent) {
            SalesAgent::create($agent);
        }
    }
}