<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use Carbon\Carbon;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            [
                'year' => 2016,
                'make' => 'Toyota',
                'model' => 'Innova',
                'variant' => 'GLX',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'kilometers' => 154339,
                'plate_number' => 'XYZ-7141',
                'colour' => 'Black',
                'with_tools' => true,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 2087363.00,
                'purchased_from' => 'Leo Garcia',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '25-Mar-22'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2012,
                'make' => 'Kia',
                'model' => 'Sorento',
                'variant' => 'Limited',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'kilometers' => 96048,
                'plate_number' => 'XYZ-5333',
                'colour' => 'Blue',
                'with_tools' => false,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 327859.00,
                'purchased_from' => 'Maria Santos',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '23-Aug-21'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2014,
                'make' => 'Nissan',
                'model' => 'Navara',
                'variant' => 'Sport',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'kilometers' => 107485,
                'plate_number' => 'JHK-3354',
                'colour' => 'Red',
                'with_tools' => true,
                'with_matting' => false,
                'with_spare_tire' => true,
                'purchase_price' => 950940.00,
                'purchased_from' => 'John Dela Cruz',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '21-Feb-17'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2010,
                'make' => 'Suzuki',
                'model' => 'Vitara',
                'variant' => 'GL',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'kilometers' => 93406,
                'plate_number' => 'ABC-2217',
                'colour' => 'White',
                'with_tools' => false,
                'with_matting' => true,
                'with_spare_tire' => false,
                'purchase_price' => 1683256.00,
                'purchased_from' => 'Joseph Lim',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '29-Apr-20'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2018,
                'make' => 'Mitsubishi',
                'model' => 'Mirage',
                'variant' => 'Premium',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'kilometers' => 174433,
                'plate_number' => 'TUV-5181',
                'colour' => 'Silver',
                'with_tools' => true,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 2102790.00,
                'purchased_from' => 'Mark Villanueva',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '15-Mar-21'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2019,
                'make' => 'Ford',
                'model' => 'EcoSport',
                'variant' => 'Base',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'kilometers' => 54526,
                'plate_number' => 'ABC-9702',
                'colour' => 'Maroon',
                'with_tools' => false,
                'with_matting' => false,
                'with_spare_tire' => true,
                'purchase_price' => 1861062.00,
                'purchased_from' => 'Kristine Lopez',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '21-Apr-23'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2024,
                'make' => 'Hyundai',
                'model' => 'Accent',
                'variant' => 'GLX',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'kilometers' => 139442,
                'plate_number' => 'ABC-9454',
                'colour' => 'Black',
                'with_tools' => true,
                'with_matting' => true,
                'with_spare_tire' => false,
                'purchase_price' => 2371088.00,
                'purchased_from' => 'Anna Mendoza',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '26-Aug-23'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2015,
                'make' => 'Mitsubishi',
                'model' => 'Strada',
                'variant' => 'Sport',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'kilometers' => 192304,
                'plate_number' => 'JHK-7384',
                'colour' => 'Blue',
                'with_tools' => false,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 1699349.00,
                'purchased_from' => 'Leo Garcia',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '18-May-18'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2020,
                'make' => 'Ford',
                'model' => 'Mustang',
                'variant' => 'Premium',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'kilometers' => 140645,
                'plate_number' => 'XYZ-3340',
                'colour' => 'Red',
                'with_tools' => true,
                'with_matting' => false,
                'with_spare_tire' => true,
                'purchase_price' => 2008264.00,
                'purchased_from' => 'Maria Santos',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '30-Apr-20'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2013,
                'make' => 'Nissan',
                'model' => 'Terra',
                'variant' => 'GL',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'kilometers' => 26455,
                'plate_number' => 'XYZ-3749',
                'colour' => 'White',
                'with_tools' => false,
                'with_matting' => true,
                'with_spare_tire' => false,
                'purchase_price' => 2191170.00,
                'purchased_from' => 'John Dela Cruz',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '30-Nov-16'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2017,
                'make' => 'Mitsubishi',
                'model' => 'Montero',
                'variant' => 'Sport',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'kilometers' => 71889,
                'plate_number' => 'NMP-8776',
                'colour' => 'Silver',
                'with_tools' => true,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 2314460.00,
                'purchased_from' => 'Joseph Lim',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '03-Feb-22'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2015,
                'make' => 'Chevrolet',
                'model' => 'Colorado',
                'variant' => 'Base',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'kilometers' => 102721,
                'plate_number' => 'XYZ-5924',
                'colour' => 'Maroon',
                'with_tools' => false,
                'with_matting' => false,
                'with_spare_tire' => true,
                'purchase_price' => 1979831.00,
                'purchased_from' => 'Mark Villanueva',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '02-Apr-15'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2024,
                'make' => 'Mazda',
                'model' => 'CX-9',
                'variant' => 'Premium',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'kilometers' => 38288,
                'plate_number' => 'JHK-9065',
                'colour' => 'Black',
                'with_tools' => true,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 2183557.00,
                'purchased_from' => 'Kristine Lopez',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '28-Nov-23'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2019,
                'make' => 'Suzuki',
                'model' => 'Swift',
                'variant' => 'GLX',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'kilometers' => 34989,
                'plate_number' => 'XYZ-2927',
                'colour' => 'Blue',
                'with_tools' => false,
                'with_matting' => true,
                'with_spare_tire' => false,
                'purchase_price' => 1788085.00,
                'purchased_from' => 'Anna Mendoza',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '09-Dec-24'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2021,
                'make' => 'Toyota',
                'model' => 'Fortuner',
                'variant' => 'Sport',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'kilometers' => 124830,
                'plate_number' => 'XYZ-5316',
                'colour' => 'Red',
                'with_tools' => true,
                'with_matting' => false,
                'with_spare_tire' => true,
                'purchase_price' => 1415056.00,
                'purchased_from' => 'Leo Garcia',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '09-Mar-21'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2015,
                'make' => 'Nissan',
                'model' => 'Navara',
                'variant' => 'GL',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'kilometers' => 146323,
                'plate_number' => 'ABC-6375',
                'colour' => 'White',
                'with_tools' => false,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 1615183.00,
                'purchased_from' => 'Maria Santos',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '16-Dec-15'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2016,
                'make' => 'Kia',
                'model' => 'Sorento',
                'variant' => 'Limited',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'kilometers' => 33426,
                'plate_number' => 'ABC-7246',
                'colour' => 'Silver',
                'with_tools' => true,
                'with_matting' => false,
                'with_spare_tire' => false,
                'purchase_price' => 958866.00,
                'purchased_from' => 'John Dela Cruz',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '20-Jun-16'),
                'spare_key' => true,
                'status' => 'Available',
            ],
            [
                'year' => 2021,
                'make' => 'Mitsubishi',
                'model' => 'Montero',
                'variant' => 'Premium',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'kilometers' => 177121,
                'plate_number' => 'NMP-5991',
                'colour' => 'Maroon',
                'with_tools' => false,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 2044008.00,
                'purchased_from' => 'Joseph Lim',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '25-Jul-21'),
                'spare_key' => false,
                'status' => 'Available',
            ],
            [
                'year' => 2020,
                'make' => 'Toyota',
                'model' => 'Innova',
                'variant' => 'GLX',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'kilometers' => 48754,
                'plate_number' => 'XYZ-2044',
                'colour' => 'Black',
                'with_tools' => true,
                'with_matting' => true,
                'with_spare_tire' => true,
                'purchase_price' => 1463909.00,
                'purchased_from' => 'Mark Villanueva',
                'purchase_date' => Carbon::createFromFormat('d-M-y', '15-Nov-20'),
                'spare_key' => true,
                'status' => 'Available',
            ],
        ];

        // Add 100 more dummy vehicles
        $additionalVehicles = $this->generateAdditionalVehicles(100);
        $vehicles = array_merge($vehicles, $additionalVehicles);

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }

    private function generateAdditionalVehicles($count)
    {
        $makes = ['Toyota', 'Honda', 'Nissan', 'Mitsubishi', 'Suzuki', 'Mazda', 'Hyundai', 'Kia', 'Ford', 'Chevrolet'];
        
        $models = [
            'Toyota' => ['Camry', 'Corolla', 'RAV4', 'Highlander', 'Prius', 'Avalon', 'Sienna', 'Tacoma', 'Tundra', '4Runner', 'Sequoia', 'Land Cruiser', 'Yaris', 'C-HR', 'Venza'],
            'Honda' => ['Civic', 'Accord', 'CR-V', 'Pilot', 'HR-V', 'Passport', 'Ridgeline', 'Insight', 'Fit', 'Odyssey', 'Element', 'S2000', 'NSX', 'Prelude', 'Integra'],
            'Nissan' => ['Altima', 'Sentra', 'Rogue', 'Murano', 'Pathfinder', 'Armada', 'Frontier', 'Titan', '370Z', 'GT-R', 'Leaf', 'Versa', 'Maxima', 'Juke', 'Cube'],
            'Mitsubishi' => ['Outlander', 'Eclipse Cross', 'Mirage', 'Lancer', 'Galant', 'Diamante', 'Montero', 'Endeavor', 'Eclipse', '3000GT', 'Starion', 'Cordia', 'Tredia', 'Sigma', 'Debonair'],
            'Suzuki' => ['Swift', 'SX4', 'Grand Vitara', 'Kizashi', 'Equator', 'XL7', 'Aerio', 'Esteem', 'Forenza', 'Reno', 'Verona', 'X-90', 'Samurai', 'Sidekick', 'Vitara'],
            'Mazda' => ['Mazda3', 'Mazda6', 'CX-5', 'CX-9', 'MX-5', 'RX-8', 'Tribute', 'B-Series', 'MPV', 'Protege', 'Millenia', '929', 'RX-7', 'Cosmo', 'Eunos'],
            'Hyundai' => ['Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Palisade', 'Veloster', 'Genesis', 'Accent', 'Azera', 'Entourage', 'Tiburon', 'XG300', 'XG350', 'Scoupe', 'Excel'],
            'Kia' => ['Forte', 'Optima', 'Sportage', 'Sorento', 'Telluride', 'Soul', 'Stinger', 'Cadenza', 'Sedona', 'Spectra', 'Amanti', 'Rondo', 'Borrego', 'Rio', 'Niro'],
            'Ford' => ['Focus', 'Fusion', 'Escape', 'Explorer', 'Expedition', 'F-150', 'Ranger', 'Mustang', 'Edge', 'Flex', 'Taurus', 'Crown Victoria', 'Thunderbird', 'GT', 'Bronco'],
            'Chevrolet' => ['Cruze', 'Malibu', 'Equinox', 'Traverse', 'Tahoe', 'Silverado', 'Colorado', 'Camaro', 'Corvette', 'Impala', 'Avalanche', 'Suburban', 'Blazer', 'Tracker', 'Cavalier']
        ];

        $variants = ['Base', 'GL', 'GLX', 'Sport', 'Premium', 'Limited', 'Touring', 'SE', 'LE', 'XLE', 'EX', 'EX-L', 'LX', 'DX', 'Type R'];
        $transmissions = ['Manual', 'Automatic'];
        $fuelTypes = ['Gasoline', 'Diesel', 'Hybrid', 'Electric'];
        $colors = ['Black', 'White', 'Silver', 'Gray', 'Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Brown', 'Gold', 'Maroon', 'Purple', 'Pink', 'Beige'];
        $statuses = ['Available', 'Sold', 'Maintenance'];
        
        $sellers = [
            'John Smith', 'Maria Garcia', 'Robert Johnson', 'Lisa Brown', 'Michael Davis', 'Sarah Wilson', 'David Martinez', 'Jennifer Anderson', 'Christopher Taylor', 'Amanda Thomas',
            'James Jackson', 'Michelle White', 'Daniel Harris', 'Ashley Martin', 'Matthew Thompson', 'Jessica Garcia', 'Andrew Martinez', 'Stephanie Robinson', 'Joshua Clark', 'Nicole Rodriguez',
            'Ryan Lewis', 'Samantha Lee', 'Brandon Walker', 'Megan Hall', 'Justin Allen', 'Rachel Young', 'Tyler Hernandez', 'Lauren King', 'Jacob Wright', 'Kayla Lopez',
            'Nathan Hill', 'Brittany Scott', 'Zachary Green', 'Danielle Adams', 'Caleb Baker', 'Victoria Gonzalez', 'Ethan Nelson', 'Amber Carter', 'Noah Mitchell', 'Sierra Perez',
            'Logan Roberts', 'Destiny Turner', 'Mason Phillips', 'Jasmine Campbell', 'Lucas Parker', 'Alexis Evans', 'Owen Edwards', 'Taylor Collins', 'Connor Stewart', 'Morgan Sanchez'
        ];

        $vehicles = [];
        $platePrefixes = ['ABC', 'XYZ', 'JHK', 'NMP', 'TUV', 'DEF', 'GHI', 'JKL', 'MNO', 'PQR', 'STU', 'VWX', 'YZA', 'BCD', 'EFG'];
        
        for ($i = 0; $i < $count; $i++) {
            $make = $makes[array_rand($makes)];
            $model = $models[$make][array_rand($models[$make])];
            $year = rand(2010, 2024);
            $kilometers = rand(10000, 300000);
            $plateNumber = $platePrefixes[array_rand($platePrefixes)] . '-' . rand(1000, 9999);
            
            // Ensure unique plate numbers
            while (Vehicle::where('plate_number', $plateNumber)->exists()) {
                $plateNumber = $platePrefixes[array_rand($platePrefixes)] . '-' . rand(1000, 9999);
            }
            
            $purchasePrice = rand(500000, 5000000);
            $purchaseDate = Carbon::now()->subDays(rand(1, 1825)); // Random date within last 5 years
            
            $vehicles[] = [
                'year' => $year,
                'make' => $make,
                'model' => $model,
                'variant' => $variants[array_rand($variants)],
                'transmission' => $transmissions[array_rand($transmissions)],
                'fuel_type' => $fuelTypes[array_rand($fuelTypes)],
                'kilometers' => $kilometers,
                'plate_number' => $plateNumber,
                'colour' => $colors[array_rand($colors)],
                'with_tools' => rand(0, 1) == 1,
                'with_matting' => rand(0, 1) == 1,
                'with_spare_tire' => rand(0, 1) == 1,
                'purchase_price' => $purchasePrice,
                'purchased_from' => $sellers[array_rand($sellers)],
                'purchase_date' => $purchaseDate,
                'spare_key' => rand(0, 1) == 1,
                'status' => $statuses[array_rand($statuses)],
                'notes' => rand(0, 1) == 1 ? 'Well maintained vehicle' : null,
            ];
        }
        
        return $vehicles;
    }
}