<?php

return [
    /*
    | Each category is hidden on /home when the user cannot view any of its items.
    | Item "page" is resolved from this key, or from config('pages.route_to_permission')[route].
    | Items with no resolvable page slug are hidden for non-admin users.
    */
    'categories' => [
        [
            'id' => 'car-reports',
            'title' => 'CAR REPORTS',
            'description' => 'Unit reports, photos, pricelist',
            'border' => 'border-primary',
            'icon_class' => 'text-primary',
            'icon' => 'fa-car',
            'items' => [
                ['label' => 'CAR PHOTOS FOLDER', 'route' => 'car-photos-folder', 'icon' => 'fa-images'],
                ['label' => 'UNIT REPORT', 'route' => 'vehicles.index', 'icon' => 'fa-car'],
                ['label' => 'UNITS MASTERLIST', 'route' => 'units-masterlist.index', 'icon' => 'fa-list'],
            ],
        ],
        [
            'id' => 'staff-reports',
            'title' => 'STAFF REPORTS',
            'description' => 'Trackers and recommendations',
            'border' => 'border-success',
            'icon_class' => 'text-success',
            'icon' => 'fa-users',
            'items' => [
                ['label' => 'BUFFING TRACKER', 'route' => 'buffing-tracker.index', 'icon' => 'fa-spray-can'],
                ['label' => 'INSURANCE TRACKER', 'route' => 'insurance-tracker.index', 'icon' => 'fa-shield-alt'],
                ['label' => 'MECHANIC TRACKER', 'route' => 'mechanic-tracker.index', 'icon' => 'fa-wrench'],
                ['label' => 'DRIVER ACTIVITY TRACKER', 'route' => 'driver-activity-tracker.index', 'icon' => 'fa-id-card'],
                ['label' => 'RECOMMENDATION TRACKER', 'route' => 'recommendation-tracker.index', 'icon' => 'fa-clipboard-check'],
                ['label' => 'SALES AGENTS', 'route' => 'staff-reports.sales-agents', 'icon' => 'fa-user-tie'],
                ['label' => 'EXECUTIVE AGENTS', 'route' => 'staff-reports.executive-agents', 'icon' => 'fa-user-shield'],
            ],
        ],
        [
            'id' => 'payments-expenses',
            'title' => 'PAYMENTS/EXPENSES REPORTS',
            'description' => 'Expenses, SOA, payroll, commission',
            'border' => 'border-warning',
            'icon_class' => 'text-warning',
            'icon' => 'fa-file-invoice-dollar',
            'items' => [
                ['label' => 'EXPENSES REPORT', 'route' => 'expenses-inventory', 'icon' => 'fa-receipt'],
                ['label' => 'SOA CASH VAULT', 'route' => 'soa.create', 'icon' => 'fa-piggy-bank'],
                ['label' => 'SALES AGENT COMMISSION', 'route' => 'sales-agent-commissions.index', 'icon' => 'fa-percent'],
                ['label' => 'GAS EXPENSES/P.O. TRACKER', 'route' => 'gas-expense-po-tracker.index', 'icon' => 'fa-gas-pump'],
                ['label' => 'PAYROLL', 'route' => 'payroll.index', 'icon' => 'fa-money-check'],
                ['label' => 'SOURCE SCREENSHOTS', 'route' => 'source-screenshots.index', 'icon' => 'fa-camera'],
            ],
        ],
        [
            'id' => 'vlogs-posts',
            'title' => 'VLOGS AND POSTS REPORTS',
            'description' => 'Video and posting trackers',
            'border' => 'border-info',
            'icon_class' => 'text-info',
            'icon' => 'fa-video',
            'items' => [
                ['label' => 'CAR VIDEO BOOST REPORT', 'route' => 'car-video-boost-report.index', 'icon' => 'fa-video'],
                ['label' => 'VIDEO AND POSTING TRACKER', 'route' => 'video-posting-tracker.index', 'icon' => 'fa-photo-video'],
            ],
        ],
        [
            'id' => 'transfers-papers',
            'title' => 'TRANSFERS/PAPERS REPORTS',
            'description' => 'Documents and transfer OR/CR',
            'border' => 'border-secondary',
            'icon_class' => 'text-secondary',
            'icon' => 'fa-file-contract',
            'items' => [
                ['label' => 'FOLLOW UP DOCUMENTS', 'route' => 'follow-up-documents.index', 'icon' => 'fa-file-alt'],
                ['label' => 'TRANSFER ORCR', 'route' => 'transfer-orcr.index', 'icon' => 'fa-right-left'],
                ['label' => 'VEHICLE REGISTRATION', 'route' => 'vehicle-registration.index', 'icon' => 'fa-id-card'],
            ],
        ],
        [
            'id' => 'customer-lists',
            'title' => 'CUSTOMER LISTS',
            'description' => 'Client and trail form lists',
            'border' => '',
            'border_style' => 'border-color: #0d6efd;',
            'icon_class' => '',
            'icon_style' => 'color: #0d6efd; border-color: #0d6efd;',
            'icon' => 'fa-address-book',
            'items' => [
                ['label' => 'CLIENT LIST', 'route' => 'client-follow-up-list.index', 'icon' => 'fa-user-friends'],
                ['label' => 'APPOINTMENT LIST', 'route' => 'appointment-list.index', 'icon' => 'fa-calendar-check'],
                ['label' => 'TRAIL FORM LIST', 'route' => 'trail-form-list.index', 'icon' => 'fa-clipboard-list'],
            ],
        ],
        [
            'id' => 'equipment-lists',
            'title' => 'EQUIPMENT LISTS',
            'description' => 'Mechanic tools and expenses',
            'border' => '',
            'border_style' => 'border-color: #fd7e14;',
            'icon_class' => '',
            'icon_style' => 'color: #fd7e14; border-color: #fd7e14;',
            'icon' => 'fa-tools',
            'items' => [
                ['label' => 'MECHANIC TOOLS/EXPENSES', 'route' => 'mechanic-tools-expenses', 'icon' => 'fa-toolbox'],
            ],
        ],
        [
            'id' => 'company-documents',
            'title' => 'COMPANY DOCUMENTS',
            'description' => 'Employee list, contracts, memos, BOLO, settings',
            'border' => '',
            'border_style' => 'border-color: #e91e63;',
            'icon_class' => '',
            'icon_style' => 'color: #e91e63; border-color: #e91e63;',
            'icon' => 'fa-folder-open',
            'items' => [
                ['label' => 'EMPLOYEE LIST', 'route' => 'employees.index', 'icon' => 'fa-users'],
                ['label' => 'CONTRACTS', 'route' => 'contracts.index', 'icon' => 'fa-file-contract'],
                ['label' => 'MEMOS', 'route' => 'memos.index', 'icon' => 'fa-sticky-note'],
                ['label' => 'AR FORM TEMPLATES', 'route' => 'document-templates.index', 'icon' => 'fa-file-invoice'],
                ['label' => 'AR TEMPLATE', 'route' => 'ar-template.index', 'icon' => 'fa-file-code'],
                ['label' => 'ONLINE AR BOLO', 'route' => 'online-ar-bolo.index', 'icon' => 'fa-globe'],
                ['label' => 'AGENT BOLO', 'route' => 'agent-bolo.index', 'icon' => 'fa-user-secret'],
            ],
        ],
        [
            'id' => 'analytics-report',
            'title' => 'ANALYTICS REPORT',
            'description' => 'Financial and sales analytics pages',
            'border' => '',
            'border_style' => 'border-color: #20c997;',
            'icon_class' => '',
            'icon_style' => 'color: #20c997; border-color: #20c997;',
            'icon' => 'fa-chart-pie',
            'items' => [
                ['label' => 'FINANCIAL REPORT', 'route' => 'analytics-report.financial', 'page' => 'analytics', 'icon' => 'fa-chart-line'],
                ['label' => 'SALES REPORT', 'route' => 'analytics-report.sales', 'page' => 'analytics', 'icon' => 'fa-chart-bar'],
                ['label' => 'SALES EXECUTIVE REPORT', 'route' => 'analytics-report.sales-executive', 'page' => 'analytics', 'icon' => 'fa-user-tie'],
            ],
        ],
        [
            'id' => 'settings',
            'title' => 'SETTINGS',
            'description' => 'System and application settings',
            'border' => '',
            'border_style' => 'border-color: #6c757d;',
            'icon_class' => '',
            'icon_style' => 'color: #6c757d; border-color: #6c757d;',
            'icon' => 'fa-cog',
            'items' => [
                ['label' => 'APPLICATION SETTINGS', 'route' => 'settings', 'icon' => 'fa-cog'],
                ['label' => 'USER ACTIVITY LOGS', 'route' => 'admin-docs', 'icon' => 'fa-history'],
            ],
        ],
        [
            'id' => 'compare',
            'title' => 'COMPARE',
            'description' => 'Compare listings across competitor websites',
            'border' => '',
            'border_style' => 'border-color: #6610f2;',
            'icon_class' => '',
            'icon_style' => 'color: #6610f2; border-color: #6610f2;',
            'icon' => 'fa-balance-scale',
            'items' => [
                ['label' => 'COMPARE CARS', 'route' => 'compare.index', 'icon' => 'fa-balance-scale'],
            ],
        ],
    ],
];
