<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Permissionable pages (for User Management > Permissions)
    | slug => label shown in the permissions matrix
    |--------------------------------------------------------------------------
    */
    'list' => [
        'home' => 'Home',
        'dashboard' => 'Dashboard',
        'analytics' => 'Analytics',
        'settings' => 'Settings',
        'settings.financing' => 'Car Price List / Financing',
        'settings.branch-locations' => 'Branch / Location',
        'payroll' => 'Payroll',
        'source-screenshots' => 'Source Screenshots',
        'car-video-boost-report' => 'Car Video Boost Report',
        'video-posting-tracker' => 'Video Posting Tracker',
        'follow-up-documents' => 'Follow-up Documents',
        'client-follow-up-list' => 'Client Follow-up List',
        'appointment-list' => 'Appointment List',
        'contracts' => 'Contracts',
        'transfer-orcr' => 'Transfer OR/CR',
        'vehicle-registration' => 'Vehicle Registration',
        'sales-agent-commissions' => 'Sales Agent Commissions',
        'expenses-inventory' => 'Expenses & Inventory',
        'expenses' => 'Expense Transactions',
        'vehicles' => 'Unit Report (Vehicles)',
        'document-templates' => 'Form Templates',
        'online-ar-bolo' => 'Online AR BOLO',
        'ar-template' => 'AR Template',
        'agent-bolo' => 'Agent BOLO',
        'sales-agents' => 'Sales Agents',
        'employees' => 'Employees',
        'pricelist' => 'Pricelist',
        'buffing-tracker' => 'Buffing Tracker',
        'insurance-tracker' => 'Insurance Tracker',
        'recommendation-tracker' => 'Recommendation Tracker',
        'staff-reports.sales-agents' => 'Staff Reports — Sales Agents',
        'staff-reports.executive-agents' => 'Staff Reports — Executive Agents',
        'gas-expense-po-tracker' => 'Gas Expense / P.O. Tracker',
        'admin-docs' => 'User Activity Logs',
        'car-photos-folder' => 'Car Photos Folder',
        'soa' => 'SOA',
    ],

    /*
    |--------------------------------------------------------------------------
    | Map route name (+ method) to page_slug and action
    | Keys: exact route name or prefix (e.g. 'vehicles' matches vehicles.*)
    | Value: [ 'page' => slug, 'action' => view|create|update|delete ]
    | For resource routes we infer: index, show, create, edit => view; store => create; update => update; destroy => delete
    |--------------------------------------------------------------------------
    */
    'route_to_permission' => [
        'home' => ['page' => 'home', 'action' => 'view'],
        'dashboard' => ['page' => 'dashboard', 'action' => 'view'],
        'cars-boost-videos' => ['page' => 'dashboard', 'action' => 'view'],
        'analytics' => ['page' => 'analytics', 'action' => 'view'],
        'settings' => ['page' => 'settings', 'action' => 'view'],
        'settings.financing.index' => ['page' => 'settings.financing', 'action' => 'view'],
        'settings.financing.store' => ['page' => 'settings.financing', 'action' => 'create'],
        'settings.financing.update' => ['page' => 'settings.financing', 'action' => 'update'],
        'settings.financing.destroy' => ['page' => 'settings.financing', 'action' => 'delete'],
        'settings.financing.schemes.store' => ['page' => 'settings.financing', 'action' => 'create'],
        'settings.financing.schemes.update' => ['page' => 'settings.financing', 'action' => 'update'],
        'settings.financing.schemes.destroy' => ['page' => 'settings.financing', 'action' => 'delete'],
        'settings.branch-locations.index' => ['page' => 'settings.branch-locations', 'action' => 'view'],
        'settings.branch-locations.store' => ['page' => 'settings.branch-locations', 'action' => 'create'],
        'settings.branch-locations.update' => ['page' => 'settings.branch-locations', 'action' => 'update'],
        'settings.branch-locations.destroy' => ['page' => 'settings.branch-locations', 'action' => 'delete'],
        'payroll.index' => ['page' => 'payroll', 'action' => 'view'],
        'source-screenshots.index' => ['page' => 'source-screenshots', 'action' => 'view'],
        'source-screenshots.create' => ['page' => 'source-screenshots', 'action' => 'view'],
        'source-screenshots.store' => ['page' => 'source-screenshots', 'action' => 'create'],
        'source-screenshots.show' => ['page' => 'source-screenshots', 'action' => 'view'],
        'source-screenshots.edit' => ['page' => 'source-screenshots', 'action' => 'view'],
        'source-screenshots.update' => ['page' => 'source-screenshots', 'action' => 'update'],
        'source-screenshots.destroy' => ['page' => 'source-screenshots', 'action' => 'delete'],
        'car-video-boost-report.index' => ['page' => 'car-video-boost-report', 'action' => 'view'],
        'video-posting-tracker.index' => ['page' => 'video-posting-tracker', 'action' => 'view'],
        'video-posting-tracker.create' => ['page' => 'video-posting-tracker', 'action' => 'view'],
        'video-posting-tracker.store' => ['page' => 'video-posting-tracker', 'action' => 'create'],
        'video-posting-tracker.show' => ['page' => 'video-posting-tracker', 'action' => 'view'],
        'video-posting-tracker.edit' => ['page' => 'video-posting-tracker', 'action' => 'view'],
        'video-posting-tracker.update' => ['page' => 'video-posting-tracker', 'action' => 'update'],
        'video-posting-tracker.destroy' => ['page' => 'video-posting-tracker', 'action' => 'delete'],
        'follow-up-documents.index' => ['page' => 'follow-up-documents', 'action' => 'view'],
        'follow-up-documents.create' => ['page' => 'follow-up-documents', 'action' => 'view'],
        'follow-up-documents.store' => ['page' => 'follow-up-documents', 'action' => 'create'],
        'follow-up-documents.show' => ['page' => 'follow-up-documents', 'action' => 'view'],
        'follow-up-documents.edit' => ['page' => 'follow-up-documents', 'action' => 'view'],
        'follow-up-documents.update' => ['page' => 'follow-up-documents', 'action' => 'update'],
        'follow-up-documents.destroy' => ['page' => 'follow-up-documents', 'action' => 'delete'],
        'client-follow-up-list.index' => ['page' => 'client-follow-up-list', 'action' => 'view'],
        'client-follow-up-list.create' => ['page' => 'client-follow-up-list', 'action' => 'view'],
        'client-follow-up-list.store' => ['page' => 'client-follow-up-list', 'action' => 'create'],
        'client-follow-up-list.show' => ['page' => 'client-follow-up-list', 'action' => 'view'],
        'client-follow-up-list.edit' => ['page' => 'client-follow-up-list', 'action' => 'view'],
        'client-follow-up-list.update' => ['page' => 'client-follow-up-list', 'action' => 'update'],
        'client-follow-up-list.destroy' => ['page' => 'client-follow-up-list', 'action' => 'delete'],
        'appointment-list.index' => ['page' => 'appointment-list', 'action' => 'view'],
        'appointment-list.create' => ['page' => 'appointment-list', 'action' => 'view'],
        'appointment-list.store' => ['page' => 'appointment-list', 'action' => 'create'],
        'appointment-list.show' => ['page' => 'appointment-list', 'action' => 'view'],
        'appointment-list.edit' => ['page' => 'appointment-list', 'action' => 'view'],
        'appointment-list.update' => ['page' => 'appointment-list', 'action' => 'update'],
        'appointment-list.destroy' => ['page' => 'appointment-list', 'action' => 'delete'],
        'contracts.index' => ['page' => 'contracts', 'action' => 'view'],
        'contracts.create' => ['page' => 'contracts', 'action' => 'view'],
        'contracts.store' => ['page' => 'contracts', 'action' => 'create'],
        'contracts.show' => ['page' => 'contracts', 'action' => 'view'],
        'contracts.edit' => ['page' => 'contracts', 'action' => 'view'],
        'contracts.update' => ['page' => 'contracts', 'action' => 'update'],
        'contracts.destroy' => ['page' => 'contracts', 'action' => 'delete'],
        'transfer-orcr.export-pdf' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.summary-report' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.index' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.create' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.store' => ['page' => 'transfer-orcr', 'action' => 'create'],
        'transfer-orcr.show' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.edit' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.update' => ['page' => 'transfer-orcr', 'action' => 'update'],
        'transfer-orcr.destroy' => ['page' => 'transfer-orcr', 'action' => 'delete'],
        'vehicle-registration.index' => ['page' => 'vehicle-registration', 'action' => 'view'],
        'vehicle-registration.create' => ['page' => 'vehicle-registration', 'action' => 'view'],
        'vehicle-registration.store' => ['page' => 'vehicle-registration', 'action' => 'create'],
        'vehicle-registration.show' => ['page' => 'vehicle-registration', 'action' => 'view'],
        'vehicle-registration.edit' => ['page' => 'vehicle-registration', 'action' => 'view'],
        'vehicle-registration.update' => ['page' => 'vehicle-registration', 'action' => 'update'],
        'vehicle-registration.destroy' => ['page' => 'vehicle-registration', 'action' => 'delete'],
        'sales-agent-commissions.index' => ['page' => 'sales-agent-commissions', 'action' => 'view'],
        'sales-agent-commissions.create' => ['page' => 'sales-agent-commissions', 'action' => 'view'],
        'sales-agent-commissions.store' => ['page' => 'sales-agent-commissions', 'action' => 'create'],
        'sales-agent-commissions.show' => ['page' => 'sales-agent-commissions', 'action' => 'view'],
        'sales-agent-commissions.edit' => ['page' => 'sales-agent-commissions', 'action' => 'view'],
        'sales-agent-commissions.update' => ['page' => 'sales-agent-commissions', 'action' => 'update'],
        'sales-agent-commissions.destroy' => ['page' => 'sales-agent-commissions', 'action' => 'delete'],
        'expenses-inventory' => ['page' => 'expenses-inventory', 'action' => 'view'],
        'expenses.create' => ['page' => 'expenses', 'action' => 'view'],
        'expenses.store' => ['page' => 'expenses', 'action' => 'create'],
        'expenses.show' => ['page' => 'expenses', 'action' => 'view'],
        'expenses.update' => ['page' => 'expenses', 'action' => 'update'],
        'expenses.destroy' => ['page' => 'expenses', 'action' => 'delete'],
        'vehicles.index' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.create' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.store' => ['page' => 'vehicles', 'action' => 'create'],
        'vehicles.show' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.edit' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.update' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.destroy' => ['page' => 'vehicles', 'action' => 'delete'],
        'document-templates.index' => ['page' => 'document-templates', 'action' => 'view'],
        'document-templates.create' => ['page' => 'document-templates', 'action' => 'view'],
        'document-templates.store' => ['page' => 'document-templates', 'action' => 'create'],
        'document-templates.edit' => ['page' => 'document-templates', 'action' => 'view'],
        'document-templates.update' => ['page' => 'document-templates', 'action' => 'update'],
        'document-templates.destroy' => ['page' => 'document-templates', 'action' => 'delete'],
        'online-ar-bolo.index' => ['page' => 'online-ar-bolo', 'action' => 'view'],
        'online-ar-bolo.create' => ['page' => 'online-ar-bolo', 'action' => 'view'],
        'online-ar-bolo.store' => ['page' => 'online-ar-bolo', 'action' => 'create'],
        'online-ar-bolo.edit' => ['page' => 'online-ar-bolo', 'action' => 'view'],
        'online-ar-bolo.update' => ['page' => 'online-ar-bolo', 'action' => 'update'],
        'online-ar-bolo.destroy' => ['page' => 'online-ar-bolo', 'action' => 'delete'],
        'ar-template.index' => ['page' => 'ar-template', 'action' => 'view'],
        'ar-template.create' => ['page' => 'ar-template', 'action' => 'view'],
        'ar-template.store' => ['page' => 'ar-template', 'action' => 'create'],
        'ar-template.edit' => ['page' => 'ar-template', 'action' => 'view'],
        'ar-template.update' => ['page' => 'ar-template', 'action' => 'update'],
        'ar-template.destroy' => ['page' => 'ar-template', 'action' => 'delete'],
        'agent-bolo.index' => ['page' => 'agent-bolo', 'action' => 'view'],
        'agent-bolo.create' => ['page' => 'agent-bolo', 'action' => 'view'],
        'agent-bolo.store' => ['page' => 'agent-bolo', 'action' => 'create'],
        'agent-bolo.show' => ['page' => 'agent-bolo', 'action' => 'view'],
        'agent-bolo.edit' => ['page' => 'agent-bolo', 'action' => 'view'],
        'agent-bolo.update' => ['page' => 'agent-bolo', 'action' => 'update'],
        'agent-bolo.destroy' => ['page' => 'agent-bolo', 'action' => 'delete'],
        'sales-agents.index' => ['page' => 'sales-agents', 'action' => 'view'],
        'sales-agents.create' => ['page' => 'sales-agents', 'action' => 'view'],
        'sales-agents.store' => ['page' => 'sales-agents', 'action' => 'create'],
        'sales-agents.show' => ['page' => 'sales-agents', 'action' => 'view'],
        'sales-agents.edit' => ['page' => 'sales-agents', 'action' => 'view'],
        'sales-agents.update' => ['page' => 'sales-agents', 'action' => 'update'],
        'sales-agents.destroy' => ['page' => 'sales-agents', 'action' => 'delete'],
        'employees.index' => ['page' => 'employees', 'action' => 'view'],
        'employees.create' => ['page' => 'employees', 'action' => 'view'],
        'employees.store' => ['page' => 'employees', 'action' => 'create'],
        'employees.show' => ['page' => 'employees', 'action' => 'view'],
        'employees.edit' => ['page' => 'employees', 'action' => 'view'],
        'employees.update' => ['page' => 'employees', 'action' => 'update'],
        'employees.destroy' => ['page' => 'employees', 'action' => 'delete'],
        'pricelist' => ['page' => 'pricelist', 'action' => 'view'],
        'buffing-tracker.index' => ['page' => 'buffing-tracker', 'action' => 'view'],
        'buffing-tracker.create' => ['page' => 'buffing-tracker', 'action' => 'view'],
        'buffing-tracker.store' => ['page' => 'buffing-tracker', 'action' => 'create'],
        'buffing-tracker.show' => ['page' => 'buffing-tracker', 'action' => 'view'],
        'buffing-tracker.edit' => ['page' => 'buffing-tracker', 'action' => 'view'],
        'buffing-tracker.update' => ['page' => 'buffing-tracker', 'action' => 'update'],
        'buffing-tracker.destroy' => ['page' => 'buffing-tracker', 'action' => 'delete'],
        'insurance-tracker.index' => ['page' => 'insurance-tracker', 'action' => 'view'],
        'insurance-tracker.create' => ['page' => 'insurance-tracker', 'action' => 'view'],
        'insurance-tracker.store' => ['page' => 'insurance-tracker', 'action' => 'create'],
        'insurance-tracker.show' => ['page' => 'insurance-tracker', 'action' => 'view'],
        'insurance-tracker.edit' => ['page' => 'insurance-tracker', 'action' => 'view'],
        'insurance-tracker.update' => ['page' => 'insurance-tracker', 'action' => 'update'],
        'insurance-tracker.destroy' => ['page' => 'insurance-tracker', 'action' => 'delete'],
        'recommendation-tracker.index' => ['page' => 'recommendation-tracker', 'action' => 'view'],
        'recommendation-tracker.create' => ['page' => 'recommendation-tracker', 'action' => 'view'],
        'recommendation-tracker.store' => ['page' => 'recommendation-tracker', 'action' => 'create'],
        'recommendation-tracker.show' => ['page' => 'recommendation-tracker', 'action' => 'view'],
        'recommendation-tracker.edit' => ['page' => 'recommendation-tracker', 'action' => 'view'],
        'recommendation-tracker.update' => ['page' => 'recommendation-tracker', 'action' => 'update'],
        'recommendation-tracker.destroy' => ['page' => 'recommendation-tracker', 'action' => 'delete'],
        'gas-expense-po-tracker.index' => ['page' => 'gas-expense-po-tracker', 'action' => 'view'],
        'gas-expense-po-tracker.store-po' => ['page' => 'gas-expense-po-tracker', 'action' => 'create'],
        'gas-expense-po-tracker.update-po' => ['page' => 'gas-expense-po-tracker', 'action' => 'update'],
        'gas-expense-po-tracker.destroy-po' => ['page' => 'gas-expense-po-tracker', 'action' => 'delete'],
        'admin-docs' => ['page' => 'admin-docs', 'action' => 'view'],
        'car-photos-folder' => ['page' => 'car-photos-folder', 'action' => 'view'],
        'soa.create' => ['page' => 'soa', 'action' => 'view'],
        'soa.store' => ['page' => 'soa', 'action' => 'create'],
        'staff-reports.sales-agents' => ['page' => 'staff-reports.sales-agents', 'action' => 'view'],
        'staff-reports.executive-agents' => ['page' => 'staff-reports.executive-agents', 'action' => 'view'],
        'staff-reports.executive-agents.store' => ['page' => 'staff-reports.executive-agents', 'action' => 'create'],
    ],
];
