<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Permissionable pages (for User Management > Permissions)
    | slug => label shown in the permissions matrix
    |--------------------------------------------------------------------------
    */
    'list' => [
        'home' => 'Home',
        'dashboard' => 'Dashboard',
        'analytics' => 'Analytics',
        'settings' => 'Settings',
        'settings.financing' => 'Car Price List / Financing',
        'settings.branch-locations' => 'Showroom',
        'payroll' => 'Payroll',
        'source-screenshots' => 'Source Screenshots',
        'car-video-boost-report' => 'Car Video Boost Report',
        'video-posting-tracker' => 'Video Posting Tracker',
        'follow-up-documents' => 'Follow-up Documents',
        'client-follow-up-list' => 'Client List',
        'appointment-list' => 'Appointment List',
        'trail-form-list' => 'Trail Form List',
        'contracts' => 'Contracts',
        'transfer-orcr' => 'Transfer OR/CR',
        'vehicle-registration' => 'Vehicle Registration',
        'sales-agent-commissions' => 'Sales Agent Commissions',
        'expenses-inventory' => 'Expenses & Inventory',
        'expenses' => 'Expense Transactions',
        'vehicles' => 'Unit Report (Vehicles)',
        'document-templates' => 'Form Templates',
        'online-ar-bolo' => 'Online AR BOLO',
        'ar-template' => 'AR Template',
        'agent-bolo' => 'Agent BOLO',
        'memos' => 'Memos',
        'sales-agents' => 'Sales Agents',
        'employees' => 'Employees',
        'units-masterlist' => 'Units Masterlist',
        'buffing-tracker' => 'Buffing Tracker',
        'insurance-tracker' => 'Insurance Tracker',
        'mechanic-tracker' => 'Mechanic Tracker',
        'driver-activity-tracker' => 'Driver Activity Tracker',
        'recommendation-tracker' => 'Recommendation Tracker',
        'staff-reports.sales-agents' => 'Staff Reports — Sales Agents',
        'staff-reports.executive-agents' => 'Staff Reports — Executive Agents',
        'gas-expense-po-tracker' => 'Gas Expense / P.O. Tracker',
        'admin-docs' => 'User Activity Logs',
        'car-photos-folder' => 'Car Photos Folder',
        'soa' => 'SOA',
    ],

    /*
    |--------------------------------------------------------------------------
    | Permission groups (User Management > Permissions matrix)
    | Mirrors home page categories. Each slug must appear in list above once.
    |--------------------------------------------------------------------------
    */
    'permission_groups' => [
        [
            'id' => 'general',
            'title' => 'General Access',
            'description' => 'Landing pages and dashboard',
            'icon' => 'fa-home',
            'pages' => ['home', 'dashboard'],
        ],
        [
            'id' => 'car-reports',
            'title' => 'CAR REPORTS',
            'description' => 'Unit reports, photos, pricelist',
            'icon' => 'fa-car',
            'pages' => ['car-photos-folder', 'vehicles', 'units-masterlist'],
        ],
        [
            'id' => 'staff-reports',
            'title' => 'STAFF REPORTS',
            'description' => 'Trackers and recommendations',
            'icon' => 'fa-users',
            'pages' => [
                'buffing-tracker',
                'insurance-tracker',
                'mechanic-tracker',
                'driver-activity-tracker',
                'recommendation-tracker',
                'staff-reports.sales-agents',
                'staff-reports.executive-agents',
                'sales-agents',
            ],
        ],
        [
            'id' => 'payments-expenses',
            'title' => 'PAYMENTS / EXPENSES REPORTS',
            'description' => 'Expenses, SOA, payroll, commission',
            'icon' => 'fa-file-invoice-dollar',
            'pages' => [
                'expenses-inventory',
                'expenses',
                'soa',
                'sales-agent-commissions',
                'gas-expense-po-tracker',
                'payroll',
                'source-screenshots',
            ],
        ],
        [
            'id' => 'vlogs-posts',
            'title' => 'VLOGS AND POSTS REPORTS',
            'description' => 'Video and posting trackers',
            'icon' => 'fa-video',
            'pages' => ['car-video-boost-report', 'video-posting-tracker'],
        ],
        [
            'id' => 'transfers-papers',
            'title' => 'TRANSFERS / PAPERS REPORTS',
            'description' => 'Documents and transfer OR/CR',
            'icon' => 'fa-file-contract',
            'pages' => ['follow-up-documents', 'transfer-orcr', 'vehicle-registration'],
        ],
        [
            'id' => 'customer-lists',
            'title' => 'CUSTOMER LISTS',
            'description' => 'Client and trail form lists',
            'icon' => 'fa-address-book',
            'pages' => ['client-follow-up-list', 'appointment-list', 'trail-form-list'],
        ],
        [
            'id' => 'company-documents',
            'title' => 'COMPANY DOCUMENTS',
            'description' => 'Employee list, contracts, memos, BOLO',
            'icon' => 'fa-folder-open',
            'pages' => [
                'employees',
                'contracts',
                'document-templates',
                'ar-template',
                'online-ar-bolo',
                'agent-bolo',
                'memos',
            ],
        ],
        [
            'id' => 'analytics-report',
            'title' => 'ANALYTICS REPORT',
            'description' => 'Financial and sales analytics',
            'icon' => 'fa-chart-pie',
            'pages' => ['analytics'],
        ],
        [
            'id' => 'settings',
            'title' => 'SETTINGS',
            'description' => 'System and application settings',
            'icon' => 'fa-cog',
            'pages' => ['settings', 'settings.financing', 'settings.branch-locations', 'admin-docs'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Map route name (+ method) to page_slug and action
    | Keys: exact route name or prefix (e.g. 'vehicles' matches vehicles.*)
    | Value: [ 'page' => slug, 'action' => view|create|update|delete ]
    | For resource routes we infer: index, show, create, edit => view; store => create; update => update; destroy => delete
    |--------------------------------------------------------------------------
    */
    'route_to_permission' => [
        'home' => ['page' => 'home', 'action' => 'view'],
        'dashboard' => ['page' => 'dashboard', 'action' => 'view'],
        'cars-boost-videos' => ['page' => 'dashboard', 'action' => 'view'],
        'analytics' => ['page' => 'analytics', 'action' => 'view'],
        'settings' => ['page' => 'settings', 'action' => 'view'],
        'settings.financing.index' => ['page' => 'settings.financing', 'action' => 'view'],
        'settings.financing.store' => ['page' => 'settings.financing', 'action' => 'create'],
        'settings.financing.update' => ['page' => 'settings.financing', 'action' => 'update'],
        'settings.financing.destroy' => ['page' => 'settings.financing', 'action' => 'delete'],
        'settings.financing.schemes.store' => ['page' => 'settings.financing', 'action' => 'create'],
        'settings.financing.schemes.update' => ['page' => 'settings.financing', 'action' => 'update'],
        'settings.financing.schemes.destroy' => ['page' => 'settings.financing', 'action' => 'delete'],
        'settings.branch-locations.index' => ['page' => 'settings.branch-locations', 'action' => 'view'],
        'settings.branch-locations.store' => ['page' => 'settings.branch-locations', 'action' => 'create'],
        'settings.branch-locations.update' => ['page' => 'settings.branch-locations', 'action' => 'update'],
        'settings.branch-locations.destroy' => ['page' => 'settings.branch-locations', 'action' => 'delete'],
        'payroll.index' => ['page' => 'payroll', 'action' => 'view'],
        'source-screenshots.index' => ['page' => 'source-screenshots', 'action' => 'view'],
        'source-screenshots.create' => ['page' => 'source-screenshots', 'action' => 'view'],
        'source-screenshots.store' => ['page' => 'source-screenshots', 'action' => 'create'],
        'source-screenshots.show' => ['page' => 'source-screenshots', 'action' => 'view'],
        'source-screenshots.edit' => ['page' => 'source-screenshots', 'action' => 'view'],
        'source-screenshots.update' => ['page' => 'source-screenshots', 'action' => 'update'],
        'source-screenshots.destroy' => ['page' => 'source-screenshots', 'action' => 'delete'],
        'car-video-boost-report.index' => ['page' => 'car-video-boost-report', 'action' => 'view'],
        'video-posting-tracker.index' => ['page' => 'video-posting-tracker', 'action' => 'view'],
        'video-posting-tracker.create' => ['page' => 'video-posting-tracker', 'action' => 'view'],
        'video-posting-tracker.store' => ['page' => 'video-posting-tracker', 'action' => 'create'],
        'video-posting-tracker.show' => ['page' => 'video-posting-tracker', 'action' => 'view'],
        'video-posting-tracker.edit' => ['page' => 'video-posting-tracker', 'action' => 'view'],
        'video-posting-tracker.update' => ['page' => 'video-posting-tracker', 'action' => 'update'],
        'video-posting-tracker.destroy' => ['page' => 'video-posting-tracker', 'action' => 'delete'],
        'follow-up-documents.index' => ['page' => 'follow-up-documents', 'action' => 'view'],
        'follow-up-documents.create' => ['page' => 'follow-up-documents', 'action' => 'view'],
        'follow-up-documents.store' => ['page' => 'follow-up-documents', 'action' => 'create'],
        'follow-up-documents.show' => ['page' => 'follow-up-documents', 'action' => 'view'],
        'follow-up-documents.edit' => ['page' => 'follow-up-documents', 'action' => 'view'],
        'follow-up-documents.update' => ['page' => 'follow-up-documents', 'action' => 'update'],
        'follow-up-documents.destroy' => ['page' => 'follow-up-documents', 'action' => 'delete'],
        'client-follow-up-list.index' => ['page' => 'client-follow-up-list', 'action' => 'view'],
        'client-follow-up-list.create' => ['page' => 'client-follow-up-list', 'action' => 'view'],
        'client-follow-up-list.store' => ['page' => 'client-follow-up-list', 'action' => 'create'],
        'client-follow-up-list.show' => ['page' => 'client-follow-up-list', 'action' => 'view'],
        'client-follow-up-list.edit' => ['page' => 'client-follow-up-list', 'action' => 'view'],
        'client-follow-up-list.update' => ['page' => 'client-follow-up-list', 'action' => 'update'],
        'client-follow-up-list.destroy' => ['page' => 'client-follow-up-list', 'action' => 'delete'],
        'appointment-list.index' => ['page' => 'appointment-list', 'action' => 'view'],
        'appointment-list.create' => ['page' => 'appointment-list', 'action' => 'view'],
        'appointment-list.store' => ['page' => 'appointment-list', 'action' => 'create'],
        'appointment-list.show' => ['page' => 'appointment-list', 'action' => 'view'],
        'appointment-list.edit' => ['page' => 'appointment-list', 'action' => 'view'],
        'appointment-list.update' => ['page' => 'appointment-list', 'action' => 'update'],
        'appointment-list.destroy' => ['page' => 'appointment-list', 'action' => 'delete'],
        'trail-form-list.index' => ['page' => 'trail-form-list', 'action' => 'view'],
        'trail-form-list.create' => ['page' => 'trail-form-list', 'action' => 'view'],
        'trail-form-list.store' => ['page' => 'trail-form-list', 'action' => 'create'],
        'trail-form-list.show' => ['page' => 'trail-form-list', 'action' => 'view'],
        'trail-form-list.edit' => ['page' => 'trail-form-list', 'action' => 'view'],
        'trail-form-list.update' => ['page' => 'trail-form-list', 'action' => 'update'],
        'trail-form-list.destroy' => ['page' => 'trail-form-list', 'action' => 'delete'],
        'contracts.index' => ['page' => 'contracts', 'action' => 'view'],
        'contracts.create' => ['page' => 'contracts', 'action' => 'view'],
        'contracts.store' => ['page' => 'contracts', 'action' => 'create'],
        'contracts.show' => ['page' => 'contracts', 'action' => 'view'],
        'contracts.edit' => ['page' => 'contracts', 'action' => 'view'],
        'contracts.update' => ['page' => 'contracts', 'action' => 'update'],
        'contracts.destroy' => ['page' => 'contracts', 'action' => 'delete'],
        'transfer-orcr.export-pdf' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.summary-report' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.index' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.create' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.store' => ['page' => 'transfer-orcr', 'action' => 'create'],
        'transfer-orcr.show' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.edit' => ['page' => 'transfer-orcr', 'action' => 'view'],
        'transfer-orcr.update' => ['page' => 'transfer-orcr', 'action' => 'update'],
        'transfer-orcr.destroy' => ['page' => 'transfer-orcr', 'action' => 'delete'],
        'vehicle-registration.index' => ['page' => 'vehicle-registration', 'action' => 'view'],
        'vehicle-registration.create' => ['page' => 'vehicle-registration', 'action' => 'view'],
        'vehicle-registration.store' => ['page' => 'vehicle-registration', 'action' => 'create'],
        'vehicle-registration.show' => ['page' => 'vehicle-registration', 'action' => 'view'],
        'vehicle-registration.edit' => ['page' => 'vehicle-registration', 'action' => 'view'],
        'vehicle-registration.update' => ['page' => 'vehicle-registration', 'action' => 'update'],
        'vehicle-registration.destroy' => ['page' => 'vehicle-registration', 'action' => 'delete'],
        'sales-agent-commissions.index' => ['page' => 'sales-agent-commissions', 'action' => 'view'],
        'sales-agent-commissions.create' => ['page' => 'sales-agent-commissions', 'action' => 'view'],
        'sales-agent-commissions.store' => ['page' => 'sales-agent-commissions', 'action' => 'create'],
        'sales-agent-commissions.show' => ['page' => 'sales-agent-commissions', 'action' => 'view'],
        'sales-agent-commissions.edit' => ['page' => 'sales-agent-commissions', 'action' => 'view'],
        'sales-agent-commissions.update' => ['page' => 'sales-agent-commissions', 'action' => 'update'],
        'sales-agent-commissions.destroy' => ['page' => 'sales-agent-commissions', 'action' => 'delete'],
        'expenses-inventory' => ['page' => 'expenses-inventory', 'action' => 'view'],
        'expenses.create' => ['page' => 'expenses', 'action' => 'view'],
        'expenses.store' => ['page' => 'expenses', 'action' => 'create'],
        'expenses.show' => ['page' => 'expenses', 'action' => 'view'],
        'expenses.update' => ['page' => 'expenses', 'action' => 'update'],
        'expenses.destroy' => ['page' => 'expenses', 'action' => 'delete'],
        'vehicles.index' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.create' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.store' => ['page' => 'vehicles', 'action' => 'create'],
        'vehicles.show' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.edit' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.update' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.destroy' => ['page' => 'vehicles', 'action' => 'delete'],
        'document-templates.index' => ['page' => 'document-templates', 'action' => 'view'],
        'document-templates.create' => ['page' => 'document-templates', 'action' => 'view'],
        'document-templates.store' => ['page' => 'document-templates', 'action' => 'create'],
        'document-templates.edit' => ['page' => 'document-templates', 'action' => 'view'],
        'document-templates.update' => ['page' => 'document-templates', 'action' => 'update'],
        'document-templates.destroy' => ['page' => 'document-templates', 'action' => 'delete'],
        'online-ar-bolo.index' => ['page' => 'online-ar-bolo', 'action' => 'view'],
        'online-ar-bolo.create' => ['page' => 'online-ar-bolo', 'action' => 'view'],
        'online-ar-bolo.store' => ['page' => 'online-ar-bolo', 'action' => 'create'],
        'online-ar-bolo.edit' => ['page' => 'online-ar-bolo', 'action' => 'view'],
        'online-ar-bolo.update' => ['page' => 'online-ar-bolo', 'action' => 'update'],
        'online-ar-bolo.destroy' => ['page' => 'online-ar-bolo', 'action' => 'delete'],
        'ar-template.index' => ['page' => 'ar-template', 'action' => 'view'],
        'ar-template.create' => ['page' => 'ar-template', 'action' => 'view'],
        'ar-template.store' => ['page' => 'ar-template', 'action' => 'create'],
        'ar-template.edit' => ['page' => 'ar-template', 'action' => 'view'],
        'ar-template.update' => ['page' => 'ar-template', 'action' => 'update'],
        'ar-template.destroy' => ['page' => 'ar-template', 'action' => 'delete'],
        'agent-bolo.index' => ['page' => 'agent-bolo', 'action' => 'view'],
        'agent-bolo.create' => ['page' => 'agent-bolo', 'action' => 'view'],
        'agent-bolo.store' => ['page' => 'agent-bolo', 'action' => 'create'],
        'agent-bolo.show' => ['page' => 'agent-bolo', 'action' => 'view'],
        'agent-bolo.edit' => ['page' => 'agent-bolo', 'action' => 'view'],
        'agent-bolo.update' => ['page' => 'agent-bolo', 'action' => 'update'],
        'agent-bolo.destroy' => ['page' => 'agent-bolo', 'action' => 'delete'],
        'memos.index' => ['page' => 'memos', 'action' => 'view'],
        'memos.create' => ['page' => 'memos', 'action' => 'view'],
        'memos.store' => ['page' => 'memos', 'action' => 'create'],
        'memos.edit' => ['page' => 'memos', 'action' => 'view'],
        'memos.update' => ['page' => 'memos', 'action' => 'update'],
        'memos.destroy' => ['page' => 'memos', 'action' => 'delete'],
        'sales-agents.index' => ['page' => 'sales-agents', 'action' => 'view'],
        'sales-agents.create' => ['page' => 'sales-agents', 'action' => 'view'],
        'sales-agents.store' => ['page' => 'sales-agents', 'action' => 'create'],
        'sales-agents.show' => ['page' => 'sales-agents', 'action' => 'view'],
        'sales-agents.edit' => ['page' => 'sales-agents', 'action' => 'view'],
        'sales-agents.update' => ['page' => 'sales-agents', 'action' => 'update'],
        'sales-agents.destroy' => ['page' => 'sales-agents', 'action' => 'delete'],
        'employees.index' => ['page' => 'employees', 'action' => 'view'],
        'employees.create' => ['page' => 'employees', 'action' => 'view'],
        'employees.store' => ['page' => 'employees', 'action' => 'create'],
        'employees.show' => ['page' => 'employees', 'action' => 'view'],
        'employees.edit' => ['page' => 'employees', 'action' => 'view'],
        'employees.update' => ['page' => 'employees', 'action' => 'update'],
        'employees.destroy' => ['page' => 'employees', 'action' => 'delete'],
        'units-masterlist.index' => ['page' => 'units-masterlist', 'action' => 'view'],
        'units-masterlist.create' => ['page' => 'units-masterlist', 'action' => 'view'],
        'units-masterlist.store' => ['page' => 'units-masterlist', 'action' => 'create'],
        'units-masterlist.show' => ['page' => 'units-masterlist', 'action' => 'view'],
        'units-masterlist.edit' => ['page' => 'units-masterlist', 'action' => 'view'],
        'units-masterlist.update' => ['page' => 'units-masterlist', 'action' => 'update'],
        'units-masterlist.destroy' => ['page' => 'units-masterlist', 'action' => 'delete'],
        'buffing-tracker.index' => ['page' => 'buffing-tracker', 'action' => 'view'],
        'buffing-tracker.create' => ['page' => 'buffing-tracker', 'action' => 'view'],
        'buffing-tracker.store' => ['page' => 'buffing-tracker', 'action' => 'create'],
        'buffing-tracker.show' => ['page' => 'buffing-tracker', 'action' => 'view'],
        'buffing-tracker.edit' => ['page' => 'buffing-tracker', 'action' => 'view'],
        'buffing-tracker.update' => ['page' => 'buffing-tracker', 'action' => 'update'],
        'buffing-tracker.destroy' => ['page' => 'buffing-tracker', 'action' => 'delete'],
        'insurance-tracker.index' => ['page' => 'insurance-tracker', 'action' => 'view'],
        'insurance-tracker.create' => ['page' => 'insurance-tracker', 'action' => 'view'],
        'insurance-tracker.store' => ['page' => 'insurance-tracker', 'action' => 'create'],
        'insurance-tracker.show' => ['page' => 'insurance-tracker', 'action' => 'view'],
        'insurance-tracker.edit' => ['page' => 'insurance-tracker', 'action' => 'view'],
        'insurance-tracker.update' => ['page' => 'insurance-tracker', 'action' => 'update'],
        'insurance-tracker.destroy' => ['page' => 'insurance-tracker', 'action' => 'delete'],
        'mechanic-tracker.index' => ['page' => 'mechanic-tracker', 'action' => 'view'],
        'mechanic-tracker.create' => ['page' => 'mechanic-tracker', 'action' => 'view'],
        'mechanic-tracker.store' => ['page' => 'mechanic-tracker', 'action' => 'create'],
        'mechanic-tracker.show' => ['page' => 'mechanic-tracker', 'action' => 'view'],
        'mechanic-tracker.edit' => ['page' => 'mechanic-tracker', 'action' => 'view'],
        'mechanic-tracker.update' => ['page' => 'mechanic-tracker', 'action' => 'update'],
        'mechanic-tracker.destroy' => ['page' => 'mechanic-tracker', 'action' => 'delete'],
        'driver-activity-tracker.index' => ['page' => 'driver-activity-tracker', 'action' => 'view'],
        'driver-activity-tracker.create' => ['page' => 'driver-activity-tracker', 'action' => 'view'],
        'driver-activity-tracker.store' => ['page' => 'driver-activity-tracker', 'action' => 'create'],
        'driver-activity-tracker.show' => ['page' => 'driver-activity-tracker', 'action' => 'view'],
        'driver-activity-tracker.edit' => ['page' => 'driver-activity-tracker', 'action' => 'view'],
        'driver-activity-tracker.update' => ['page' => 'driver-activity-tracker', 'action' => 'update'],
        'driver-activity-tracker.destroy' => ['page' => 'driver-activity-tracker', 'action' => 'delete'],
        'recommendation-tracker.index' => ['page' => 'recommendation-tracker', 'action' => 'view'],
        'recommendation-tracker.create' => ['page' => 'recommendation-tracker', 'action' => 'view'],
        'recommendation-tracker.store' => ['page' => 'recommendation-tracker', 'action' => 'create'],
        'recommendation-tracker.show' => ['page' => 'recommendation-tracker', 'action' => 'view'],
        'recommendation-tracker.edit' => ['page' => 'recommendation-tracker', 'action' => 'view'],
        'recommendation-tracker.update' => ['page' => 'recommendation-tracker', 'action' => 'update'],
        'recommendation-tracker.destroy' => ['page' => 'recommendation-tracker', 'action' => 'delete'],
        'gas-expense-po-tracker.index' => ['page' => 'gas-expense-po-tracker', 'action' => 'view'],
        'gas-expense-po-tracker.store-po' => ['page' => 'gas-expense-po-tracker', 'action' => 'create'],
        'gas-expense-po-tracker.update-po' => ['page' => 'gas-expense-po-tracker', 'action' => 'update'],
        'gas-expense-po-tracker.destroy-po' => ['page' => 'gas-expense-po-tracker', 'action' => 'delete'],
        'admin-docs' => ['page' => 'admin-docs', 'action' => 'view'],
        'car-photos-folder' => ['page' => 'car-photos-folder', 'action' => 'view'],
        'soa.create' => ['page' => 'soa', 'action' => 'view'],
        'soa.store' => ['page' => 'soa', 'action' => 'create'],
        'staff-reports.sales-agents' => ['page' => 'staff-reports.sales-agents', 'action' => 'view'],
        'staff-reports.executive-agents' => ['page' => 'staff-reports.executive-agents', 'action' => 'view'],
        'staff-reports.executive-agents.show' => ['page' => 'staff-reports.executive-agents', 'action' => 'view'],
        'staff-reports.executive-agents.store' => ['page' => 'staff-reports.executive-agents', 'action' => 'create'],
        'settings.users.index' => ['page' => 'settings', 'action' => 'view'],
        'settings.users.create' => ['page' => 'settings', 'action' => 'view'],
        'settings.users.store' => ['page' => 'settings', 'action' => 'create'],
        'settings.users.edit' => ['page' => 'settings', 'action' => 'view'],
        'settings.users.update' => ['page' => 'settings', 'action' => 'update'],
        'settings.users.destroy' => ['page' => 'settings', 'action' => 'delete'],
        'settings.users.permissions' => ['page' => 'settings', 'action' => 'view'],
        'settings.users.permissions.update' => ['page' => 'settings', 'action' => 'update'],
        'analytics-report.financial' => ['page' => 'analytics', 'action' => 'view'],
        'analytics-report.financial.export' => ['page' => 'analytics', 'action' => 'view'],
        'analytics-report.sales' => ['page' => 'analytics', 'action' => 'view'],
        'analytics-report.sales-executive' => ['page' => 'analytics', 'action' => 'view'],
        'car-video-boost-report.store-ad' => ['page' => 'car-video-boost-report', 'action' => 'create'],
        'car-video-boost-report.update-ad' => ['page' => 'car-video-boost-report', 'action' => 'update'],
        'car-video-boost-report.destroy-ad' => ['page' => 'car-video-boost-report', 'action' => 'delete'],
        'expenses-inventory.export' => ['page' => 'expenses-inventory', 'action' => 'view'],
        'expenses.items.store' => ['page' => 'expenses', 'action' => 'create'],
        'expenses.items.update' => ['page' => 'expenses', 'action' => 'update'],
        'expenses.items.destroy' => ['page' => 'expenses', 'action' => 'delete'],
        'expenses.items.receipts.store' => ['page' => 'expenses', 'action' => 'create'],
        'expenses.items.receipts.destroy' => ['page' => 'expenses', 'action' => 'delete'],
        'expenses.vehicle-categories.store' => ['page' => 'expenses', 'action' => 'create'],
        'tools.store' => ['page' => 'expenses-inventory', 'action' => 'create'],
        'tools.show' => ['page' => 'expenses-inventory', 'action' => 'view'],
        'tools.update' => ['page' => 'expenses-inventory', 'action' => 'update'],
        'tools.destroy' => ['page' => 'expenses-inventory', 'action' => 'delete'],
        'tools.history' => ['page' => 'expenses-inventory', 'action' => 'view'],
        'vehicles.export-list' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.export' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.archive' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.posted-price.update' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.posted-price.delete' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.sold-price.update' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.sold-price.delete' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.incentive.update' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.images.index' => ['page' => 'vehicles', 'action' => 'view'],
        'vehicles.images.store' => ['page' => 'vehicles', 'action' => 'create'],
        'vehicles.images.primary' => ['page' => 'vehicles', 'action' => 'update'],
        'vehicles.images.destroy' => ['page' => 'vehicles', 'action' => 'delete'],
        'gas-expense-po-tracker.export-pdf' => ['page' => 'gas-expense-po-tracker', 'action' => 'view'],
        'gas-expense-po-tracker.store-gas' => ['page' => 'gas-expense-po-tracker', 'action' => 'create'],
        'gas-expense-po-tracker.update-gas' => ['page' => 'gas-expense-po-tracker', 'action' => 'update'],
        'gas-expense-po-tracker.destroy-gas' => ['page' => 'gas-expense-po-tracker', 'action' => 'delete'],
        'recommendation-tracker.images.destroy' => ['page' => 'recommendation-tracker', 'action' => 'delete'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Route name prefix => page slug (for activity logging on nested routes)
    |--------------------------------------------------------------------------
    */
    'route_prefix_to_page' => [
        'vehicles.' => 'vehicles',
        'soa.' => 'soa',
        'expenses.' => 'expenses',
        'units-masterlist.' => 'units-masterlist',
        'agent-bolo.' => 'agent-bolo',
        'document-templates.' => 'document-templates',
        'gas-expense-po-tracker.' => 'gas-expense-po-tracker',
    ],
];
